7.4. Меняй-удаляй (часть 1)
htmlacademy-ecmascript/169447-big-trip-15 pull request #12
Opened 2021-08-31 14:26 UTC by ikashyntseva

2021-08-31 15:23 UTC, what1s1ove requested changes

2021-08-31 15:23 UTC, what1s1ove commented on src/presenter/trip.js
> +      case UserAction.UPDATE_EVENT:
скобки 🦐

2021-08-31 15:23 UTC, what1s1ove commented on src/presenter/trip.js
> +      case UpdateType.PATCH:
и тут:

2021-08-31 15:23 UTC, what1s1ove commented on src/utils/abstract-observer.js
> +export default class AbstractObserver {
экспорт только внизу

2021-08-31 15:23 UTC, what1s1ove commented on src/view/event-add.js
> +    return Object.assign(
у тебя где-то `Object.assing`, а где-то через спред (`{ ...obj }`)
Используй что-то одно 🙏

2021-08-31 19:42 UTC, ikashyntseva commented on src/presenter/trip.js
> +      case UserAction.UPDATE_EVENT:
Исправила

2021-08-31 19:42 UTC, ikashyntseva commented on src/presenter/trip.js
> +      case UpdateType.PATCH:
Исправила

2021-08-31 19:42 UTC, ikashyntseva commented on src/utils/abstract-observer.js
> +export default class AbstractObserver {
Исправила

2021-08-31 19:42 UTC, ikashyntseva commented on src/view/event-add.js
> +    return Object.assign(
Исправила

2021-09-01 06:49 UTC, what1s1ove approved these changes

2021-09-01 06:49 UTC, merged