3.13. Революция или эволюция?
htmlacademy-ecmascript/169447-big-trip-15 pull request #6
Opened 2021-08-07 13:29 UTC by ikashyntseva

2021-08-07 13:54 UTC, ZubkoWhatislove requested changes

2021-08-07 13:54 UTC, ZubkoWhatislove commented on src/enums.js
> +const Type = {
Добавь чуть больше контекста, а то тайп слишком тяжело воспринять)

2021-08-07 13:54 UTC, ZubkoWhatislove commented on src/enums.js
> +const Type = {
Но то что вынесла это в сразу в енам - 👍

2021-08-07 13:54 UTC, ZubkoWhatislove commented on src/utils.js
> +      break;
```suggestion
    case RenderPosition.AFTERBEGIN: {
      container.prepend(element);
      break;
    }
```
скобки - обязательно. Добавить на все

2021-08-07 13:54 UTC, ZubkoWhatislove commented on src/utils.js
> +  return newElement.firstChild;
```suggestion
  return newElement.firstElementChild;
```
Просто `firstChild` считает пробелы за детей 😥

2021-08-07 14:20 UTC, ikashyntseva commented on src/utils.js
> +  return newElement.firstChild;
Видела, но почему-то просто убрала пробел :) 
Исправила

2021-08-07 14:20 UTC, ikashyntseva commented on src/enums.js
> +const Type = {
Исправила

2021-08-07 14:22 UTC, ikashyntseva commented on src/utils.js
> +      break;
Исправила

2021-08-08 06:22 UTC, ZubkoWhatislove approved these changes

2021-08-08 06:22 UTC, merged