3.13. Революция или эволюция? (часть 2)
htmlacademy-ecmascript/169447-big-trip-15 pull request #7
Opened 2021-08-08 10:10 UTC by ikashyntseva

2021-08-08 10:25 UTC, what1s1ove requested changes

2021-08-08 10:25 UTC, what1s1ove commented on src/utils.js
> +  if (evt.key === 'Escape' || evt.key === 'Esc') {
```suggestion
  if (evt.key === KeydownKey.ESCAPE) {
```

2021-08-08 10:25 UTC, what1s1ove commented on src/view/event-details-section.js
> +            for (let j = 0; j < selectedEventTypeOffers.length; j++) {
тут сложнота конечно, но мы подправим когда будем фетчить данные с сервера

2021-08-08 10:25 UTC, what1s1ove commented on src/view/event-edit.js
> +      Array.from(this._element.querySelectorAll('.event__type-input')).forEach((eventTypeInput) => eventTypeInput.addEventListener('click', (evt) => {
```suggestion
      this._element.querySelectorAll('.event__type-input').forEach((eventTypeInput) => eventTypeInput.addEventListener('click', (evt) => {
```
`forEach` доступен в коллекции нод)

2021-08-08 10:50 UTC, ikashyntseva commented on src/view/event-details-section.js
> +            for (let j = 0; j < selectedEventTypeOffers.length; j++) {
Вот да, мне тут самой не нравится реализация

2021-08-08 10:59 UTC, ikashyntseva commented on src/view/event-edit.js
> +      Array.from(this._element.querySelectorAll('.event__type-input')).forEach((eventTypeInput) => eventTypeInput.addEventListener('click', (evt) => {
Я почему-то думала недоступен(( Исправила

2021-08-08 10:59 UTC, ikashyntseva commented on src/utils.js
> +  if (evt.key === 'Escape' || evt.key === 'Esc') {
Исправила

2021-08-09 03:46 UTC, what1s1ove approved these changes

2021-08-09 03:46 UTC, merged